name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
    - name: Set up Rust
      uses: actions/checkout@v3
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - run: rustup component add clippy
    - run: cargo install cargo-audit
    
    - name: Build
      run: cargo build --verbose
    - name: Clippy
      run: cargo clippy --verbose --all-targets --all-features -- -D warnings
    - name: Audit
      run: cargo audit
